services:
  backend:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    labels:
      - "traefik.enable=false"

  configurator:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=false"

  create-site:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
        bench --site frontend install-app crm;
        bench --site frontend install-app drive;
        bench --site frontend install-app helpdesk;
        bench --site frontend install-app hrms;
        bench --site frontend install-app raven;
        bench --site frontend install-app payments;
        bench --site frontend install-app frappe_whatsapp;
    labels:
      - "traefik.enable=false"

  db:
    image: mariadb:10.6
    networks:
      - frappe_docker_network
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  frontend:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frappe-all-frontend-http.rule=Host(`sub.yourdomain.com`)"
      - "traefik.http.routers.frappe-all-frontend-http.entrypoints=web"
      - "traefik.http.routers.frappe-all-frontend-http.service=frappe-all-frontend-http-service"
      - "traefik.http.services.frappe-all-frontend-http-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.frappe-all-frontend-https.rule=Host(`sub.yourdomain.com`)"
      - "traefik.http.routers.frappe-all-frontend-https.entrypoints=websecure"
      - "traefik.http.routers.frappe-all-frontend-https.service=frappe-all-frontend-https-service"
      - "traefik.http.services.frappe-all-frontend-https-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.frappe-all-frontend-https.tls=true"
      - "traefik.http.routers.frappe-all-frontend-https.tls.certresolver=webResolver"

  queue-long:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=false"

  queue-short:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=false"

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data
    labels:
      - "traefik.enable=false"

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=false"

  scheduler:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=false"

  websocket:
    image: frappe-all:1.0.0
    networks:
      - frappe_docker_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=false"

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./db-data
      o: bind
  redis-queue-data:
    driver: local
    driver_opts:
      type: none
      device: ./redis-queue-data
      o: bind
  sites:
    driver: local
    driver_opts:
      type: none
      device: ./sites
      o: bind
  logs:
    driver: local
    driver_opts:
      type: none
      device: ./logs
      o: bind

networks:
  frappe_docker_network:
    external: true
